// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZKUU4AY9ItdWKoI1dMuZb37A38No-dw',
    appId: '1:416984242145:web:bf3cd1e20852ca60e924a0',
    messagingSenderId: '416984242145',
    projectId: 'chatappgit-39234',
    authDomain: 'chatappgit-39234.firebaseapp.com',
    storageBucket: 'chatappgit-39234.firebasestorage.app',
    measurementId: 'G-JQDMVL7Q2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgr_3HMQRlAh3coRl4HTgxpuFYVzeVRGE',
    appId: '1:416984242145:android:5b32afe0b0610dfee924a0',
    messagingSenderId: '416984242145',
    projectId: 'chatappgit-39234',
    storageBucket: 'chatappgit-39234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4OBb4gpvRTZ4PrWP5JKUC4oMK0fNf-mQ',
    appId: '1:416984242145:ios:2934721dab522841e924a0',
    messagingSenderId: '416984242145',
    projectId: 'chatappgit-39234',
    storageBucket: 'chatappgit-39234.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4OBb4gpvRTZ4PrWP5JKUC4oMK0fNf-mQ',
    appId: '1:416984242145:ios:2934721dab522841e924a0',
    messagingSenderId: '416984242145',
    projectId: 'chatappgit-39234',
    storageBucket: 'chatappgit-39234.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeZKUU4AY9ItdWKoI1dMuZb37A38No-dw',
    appId: '1:416984242145:web:dfa0f8a7cecface8e924a0',
    messagingSenderId: '416984242145',
    projectId: 'chatappgit-39234',
    authDomain: 'chatappgit-39234.firebaseapp.com',
    storageBucket: 'chatappgit-39234.firebasestorage.app',
    measurementId: 'G-R4L9RPFLC3',
  );
}
